export const SET_MENTORS_LIST = 'SET_MENTORS_LIST';
export const SET_CHOOSED_MENTOR = 'SET_CHOOSED_MENTOR';
export const UNCHOOSE_CHOOSED_MENTOR = 'UNCHOOSE_CHOOSED_MENTOR';

export const SET_AUTHORIZED_STATUS = 'SET_AUTHORIZED_STATUS';